name: Build and Publish Ionic App

on:
  push:
      branches:
      - master
      - test

# env:
#   SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
#   KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
#   KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
#   KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
#   KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

jobs:
  variables:
    runs-on: ubuntu-latest
    name: Set Deploy Environment Variables
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version information
        run: ./extract_version.sh

      - name: Get environment
        run: echo "DEPLOY_ENVIRONMENT=$([[ ${{ github.ref }} == 'refs/heads/master' ]] && echo 'prod' || echo 'test')" >> $GITHUB_ENV

      - name: Print DEPLOY_ENVIRONMENT variable
        run: echo "The environment is $DEPLOY_ENVIRONMENT"

  docker:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dataquest:latest
            ${{ secrets.DOCKER_USERNAME }}/dataquest:${{ env.VERSION_NAME }}-${{ env.DEPLOY_ENVIRONMENT }}.${{ env.VERSION_CODE }}
            ${{ secrets.DOCKER_USERNAME }}/dataquest:${{ github.sha }}



#  The  SERVICE_ACCOUNT_JSON  is a secret that we will add to the repository.
#  To add the secret, go to the repository settings, then click on the  Secrets  tab. Click on  New repository secret  and add the  SERVICE_ACCOUNT_JSON  secret.
#  The value of the secret is the content of the  service-account.json  file.
#  Now, let’s create a new branch and push the changes to the repository.
#  git checkout -b test
